language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: TRAVIS_NODE_VERSION="6"
        - os: linux
          python: 3.3
          env: TRAVIS_NODE_VERSION="8"
        - os: osx
          python: 3.4
          env: TRAVIS_NODE_VERSION="8"
        - os: linux
          python: 3.5
          env: TRAVIS_NODE_VERSION="9"
        - os: osx
          python: 3.6
          env: TRAVIS_NODE_VERSION="9"

node_js:
  - 'node'

env:
  - TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

script: "./build ci"
