name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Build ${{ matrix.os }} (Node ${{ matrix.node-version }}, Python ${{ matrix.python-version }} )
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
        python-version: [3.8, '3.10', 3.11]
        include:
          - python-version: 3.8 
            node-version: 16
          - python-version: '3.10'
            node-version: 18
          - python-version: 3.11
            node-version: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package*.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Make all (Windows)
        if: matrix.os == 'windows'
        run: make all
      - name: Make CI (Non-windows)
        if: matrix.os != 'windows'
        run: make ci
