# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release PR

on:
  push:
    branches:
      - 'staging/gh-pages'
      - 'staging/main'
      - 'staging/release'


jobs:
  PR-from-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: pull-request gh-pages
        if: github.ref == 'refs/heads/staging/gh-pages'
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Pulling staging/gh-pages into gh-pages"
          source_branch: "staging/gh-pages"
          destination_branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: pull-request main
        if: github.ref == 'refs/heads/staging/main'
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Pulling staging/main into main"
          source_branch: "staging/main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: pull-request release
        if: github.ref == 'refs/heads/staging/release'
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Pulling staging/release into release"
          source_branch: "staging/release"
          destination_branch: "release"
          github_token: ${{ secrets.GITHUB_TOKEN }}
